# Generated by Django 3.1.2 on 2020-12-07 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.IntegerField()),
                ('etaj', models.CharField(max_length=250)),
                ('Ax', models.IntegerField()),
                ('Ay', models.IntegerField()),
                ('Bx', models.IntegerField()),
                ('By', models.IntegerField()),
                ('Cx', models.IntegerField()),
                ('Cy', models.IntegerField()),
                ('Dx', models.IntegerField()),
                ('Dy', models.IntegerField()),
                ('nr_locuri', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameR', models.CharField(max_length=250)),
                ('lungime', models.IntegerField()),
                ('latime', models.IntegerField()),
                ('adresa', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('ora', models.TimeField(auto_now=True)),
                ('timp', models.TimeField()),
                ('telefon', models.CharField(max_length=14)),
                ('nume_pers', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('id_M', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.mese')),
                ('id_U', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_stele', models.IntegerField()),
                ('mesaj', models.CharField(max_length=2000)),
                ('data', models.DateTimeField(auto_now=True)),
                ('id_R', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.restaurant')),
                ('id_U', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pereti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.IntegerField(null=True)),
                ('etaj', models.CharField(max_length=250)),
                ('Ax', models.IntegerField()),
                ('Ay', models.IntegerField()),
                ('Bx', models.IntegerField()),
                ('By', models.IntegerField()),
                ('Cx', models.IntegerField()),
                ('Cy', models.IntegerField()),
                ('Dx', models.IntegerField()),
                ('Dy', models.IntegerField()),
                ('id_R', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='mese',
            name='id_R',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.restaurant'),
        ),
    ]
