# Generated by Django 3.1.2 on 2021-03-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitudine',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitudine',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
    ]
