# Generated by Django 3.1.2 on 2021-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rezervari',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rezervari',
            name='ora',
            field=models.TimeField(),
        ),
    ]
