# Generated by Django 3.1.2 on 2020-10-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
